// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACahLmEMLYMdue9wx9l4EY9YXza6K4LH0',
    appId: '1:477653563777:web:01235fa03a1d491ac6d080',
    messagingSenderId: '477653563777',
    projectId: 'sane-machine-3e910',
    authDomain: 'sane-machine-3e910.firebaseapp.com',
    storageBucket: 'sane-machine-3e910.firebasestorage.app',
    measurementId: 'G-0XC37MC56B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzr2nN8ljx9_-UqujTW1zZ2Ls5mOd_mXw',
    appId: '1:477653563777:android:6bd7a70be410050fc6d080',
    messagingSenderId: '477653563777',
    projectId: 'sane-machine-3e910',
    storageBucket: 'sane-machine-3e910.firebasestorage.app',
  );

}